### ISSUE TITLE
< in checklist eats following text

### ISSUE THREAD

**Issue by juhp** [mojombo/github-flavored-markdown#60]
Recently the rendering of checklists seems to have changed:

```
- [ ] this renders okay
- [ ] but less-than and following text disappears: < can you can see me?
```

renders as
- [ ] this renders okay
- [ ] but less-than and following text disappears: < can you can see me?

This seems like a bug or a regression.  Is it intentional?

**Comment by juhp** [comment]
- [ ] less-than and following text disappears http://google.com

**Comment by felixonmars** [comment]
Looks like it's fixed now :)

**Comment by juhp** [comment]
Yes it is.
